language: python
python:
- 2.7
- 3.4
- 3.5
- pypy
before_install:
- pip install nose coverage codecov
- pip install -r requires/testing.txt
install:
- pip install -e .
script: nosetests
after_success:
- codecov
sudo: false
